name: CI

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - "**/Cargo.toml"
    tags-ignore: ["**"]
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "**.md"
      - "**/Cargo.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Check formatting
        run: cargo fmt -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run tests
        run: cargo test -v --no-fail-fast
